# Directory to search for podcast audio files in
path: /tmp/pods/

# Directory to store extracted images in
imagePath: /tmp/pod-image/

# Directory to store the database in (Majorpodo uses this to cache information scraped from media files)
databasePath: /tmp/pod-database/

# Base URL for RSS feeds
httpRoot: http://localhost:3000/

# Where the HTTP server should listen for requests
# Takes the options listed at: https://nodejs.org/api/net.html#net_server_listen_options_callback
listen:
  port: 3000
  host: 127.0.0.1 # 0.0.0.0 will listen on all network interfaces

# Usernames and passwords
# Leave commented out for a publicly accessible podcast service or if you are handling authentication elsewhere
# users:
#   - username: podcast
#     password: example-password

# A string containing a regular expression suitable for passing to JavaScript's
# `RegExp` constructor function which identifies the audio files to try to
# include as podcasts. See also https://regex101.com/
audioRegExp: (?:m4a|mp3)$

# Path to write log files to
# Majorpodo also logs to STDOUT, leave this commented out if that is sufficient.
# e.g. if you are using pm2 to manage the log files
#
# logFile: /tmp/majorpodo.log

# Third-party audio files can have information in the metadata which makes it
# hard to group properly. This allows you to transform that data.
# Note that YML requires slash characters to be escaped
filters:
  remove:
    # Regular expressions which match sections of album titles to be removed
    # entirely.
    - "[:-] Series \\d+(?: Omnibus)?$"
    - ": Christmas Special(?: \\d+)?$"
    - "\\(Omnibus\\)$"
  replace:
    # Regular expressions and plain strings to replace any title that is a match
    # for them with. This is used to normalise variations in title (e.g. should
    # a show sometimes end a title in a question mark and sometimes omit it, or
    # to give each season a subtitle (like Hexagonal Phase)).
    - expression: "Hitchhiker's Guide to the Galaxy"
      title: "Hitchhiker's Guide to the Galaxy"
    - expression: 'How to Survive the Roman Empire, by Pliny and Me'
      title: 'How to Survive the Roman Empire, by Pliny and Me'
